### ISSUE TITLE
No scroll in content viewer cant view all of JSON content

### ISSUE THREAD

**Issue by rbrastad** [enonic/app-content-viewer#1]
I've installed the content viewer but I can't scroll the JSON content. I see the content in SOURCE so there must be a CSS issue.

OS: Ubuntu
Browser: Chrome

**Comment by aro** [comment]
Could you check if it's still a problem in the latest snapshot?
Actually Chrome is the one that was working better. Which Chrome version is it?

**Comment by rbrastad** [comment]
Hey,

I'm using Ubuntu and using Chrome Version 47.0.2526.106 (64-bit)

Still the same problem after the fix. If I edit CSS in the PRE tag I can get the scrollbar but not in the CODE tag. See screenshot

![image](https://cloud.githubusercontent.com/assets/1395978/12057527/554f7828-af42-11e5-8e6c-8c658d87ebfe.png)

**Comment by Bellfalasch** [comment]
Doesn't even your scroll wheel on the mouse work?

What happens if you resize the right hand column?

**Comment by alansemenov** [comment]
Hei Runar,

We fixed the issue with scrolling but you'll have to wait for 6.4 to get the fix.
We also fixed the UI to make it look a bit more XP-ish (this you can get already now, it's a part of the app).
![image](https://cloud.githubusercontent.com/assets/11612490/12174223/c4c74e0a-b55b-11e5-8676-2747b039c062.png)

**Comment by rbrastad** [comment]
That great look really nice :)
